# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaIniciarSesion(object):
    def setupUi(self, VentanaIniciarSesion):
        VentanaIniciarSesion.setObjectName("VentanaIniciarSesion")
        VentanaIniciarSesion.resize(640, 480)
        self.gridLayout_2 = QtWidgets.QGridLayout(VentanaIniciarSesion)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(196, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_iniciar_sesion = QtWidgets.QPushButton(parent=VentanaIniciarSesion)
        self.btn_iniciar_sesion.setObjectName("btn_iniciar_sesion")
        self.gridLayout.addWidget(self.btn_iniciar_sesion, 7, 0, 1, 1)
        self.txt_contrasenia = QtWidgets.QLineEdit(parent=VentanaIniciarSesion)
        self.txt_contrasenia.setText("")
        self.txt_contrasenia.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_contrasenia.setObjectName("txt_contrasenia")
        self.gridLayout.addWidget(self.txt_contrasenia, 4, 0, 1, 3)
        self.btn_mostrar_ocultar_contrasenia = QtWidgets.QPushButton(parent=VentanaIniciarSesion)
        self.btn_mostrar_ocultar_contrasenia.setObjectName("btn_mostrar_ocultar_contrasenia")
        self.gridLayout.addWidget(self.btn_mostrar_ocultar_contrasenia, 3, 2, 1, 1)
        self.btn_registrarse = QtWidgets.QPushButton(parent=VentanaIniciarSesion)
        self.btn_registrarse.setObjectName("btn_registrarse")
        self.gridLayout.addWidget(self.btn_registrarse, 7, 2, 1, 1)
        self.lbl_correo = QtWidgets.QLabel(parent=VentanaIniciarSesion)
        self.lbl_correo.setObjectName("lbl_correo")
        self.gridLayout.addWidget(self.lbl_correo, 0, 0, 1, 3)
        self.txt_correo = QtWidgets.QLineEdit(parent=VentanaIniciarSesion)
        self.txt_correo.setText("")
        self.txt_correo.setObjectName("txt_correo")
        self.gridLayout.addWidget(self.txt_correo, 1, 0, 2, 3)
        self.btn_olvide_contrasenia = QtWidgets.QPushButton(parent=VentanaIniciarSesion)
        self.btn_olvide_contrasenia.setObjectName("btn_olvide_contrasenia")
        self.gridLayout.addWidget(self.btn_olvide_contrasenia, 5, 0, 1, 3)
        self.lbl_contrasenia = QtWidgets.QLabel(parent=VentanaIniciarSesion)
        self.lbl_contrasenia.setObjectName("lbl_contrasenia")
        self.gridLayout.addWidget(self.lbl_contrasenia, 3, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(196, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 3, 1, 1, 1)

        self.retranslateUi(VentanaIniciarSesion)
        QtCore.QMetaObject.connectSlotsByName(VentanaIniciarSesion)
        VentanaIniciarSesion.setTabOrder(self.txt_correo, self.txt_contrasenia)
        VentanaIniciarSesion.setTabOrder(self.txt_contrasenia, self.btn_mostrar_ocultar_contrasenia)
        VentanaIniciarSesion.setTabOrder(self.btn_mostrar_ocultar_contrasenia, self.btn_olvide_contrasenia)
        VentanaIniciarSesion.setTabOrder(self.btn_olvide_contrasenia, self.btn_iniciar_sesion)
        VentanaIniciarSesion.setTabOrder(self.btn_iniciar_sesion, self.btn_registrarse)

    def retranslateUi(self, VentanaIniciarSesion):
        _translate = QtCore.QCoreApplication.translate
        VentanaIniciarSesion.setWindowTitle(_translate("VentanaIniciarSesion", "Form"))
        self.btn_iniciar_sesion.setText(_translate("VentanaIniciarSesion", "Iniciar Sesión"))
        self.txt_contrasenia.setPlaceholderText(_translate("VentanaIniciarSesion", "Ingresa tu contraseña"))
        self.btn_mostrar_ocultar_contrasenia.setText(_translate("VentanaIniciarSesion", "Mostrar"))
        self.btn_registrarse.setText(_translate("VentanaIniciarSesion", "Registrarse"))
        self.lbl_correo.setText(_translate("VentanaIniciarSesion", "Correo electrónico:"))
        self.txt_correo.setPlaceholderText(_translate("VentanaIniciarSesion", "Ingresa tu correo electrónico"))
        self.btn_olvide_contrasenia.setText(_translate("VentanaIniciarSesion", "Olvidé la contraseña"))
        self.lbl_contrasenia.setText(_translate("VentanaIniciarSesion", "Contraseña"))
