# Form implementation generated from reading ui file 'panel_bienvenida.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PanelBienvenida(object):
    def setupUi(self, PanelBienvenida):
        PanelBienvenida.setObjectName("PanelBienvenida")
        PanelBienvenida.resize(640, 480)
        self.gridLayout = QtWidgets.QGridLayout(PanelBienvenida)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 192, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(239, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=PanelBienvenida)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lbl_nombre_usuario = QtWidgets.QLabel(parent=PanelBienvenida)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_nombre_usuario.setFont(font)
        self.lbl_nombre_usuario.setText("")
        self.lbl_nombre_usuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_nombre_usuario.setObjectName("lbl_nombre_usuario")
        self.verticalLayout.addWidget(self.lbl_nombre_usuario)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(239, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 192, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)

        self.retranslateUi(PanelBienvenida)
        QtCore.QMetaObject.connectSlotsByName(PanelBienvenida)

    def retranslateUi(self, PanelBienvenida):
        _translate = QtCore.QCoreApplication.translate
        PanelBienvenida.setWindowTitle(_translate("PanelBienvenida", "Form"))
        self.label.setText(_translate("PanelBienvenida", "Bienvenido/a"))
