# Form implementation generated from reading ui file 'panel_metas.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PanelMetas(object):
    def setupUi(self, PanelMetas):
        PanelMetas.setObjectName("PanelMetas")
        PanelMetas.resize(523, 247)
        self.gridLayout = QtWidgets.QGridLayout(PanelMetas)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=PanelMetas)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=PanelMetas)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.btn_nueva_meta = QtWidgets.QPushButton(parent=PanelMetas)
        self.btn_nueva_meta.setObjectName("btn_nueva_meta")
        self.horizontalLayout.addWidget(self.btn_nueva_meta)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(parent=PanelMetas)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 411, 83))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(10, 20, 402, 74))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.seccion_metas = QtWidgets.QFrame(parent=self.widget)
        self.seccion_metas.setMinimumSize(QtCore.QSize(400, 20))
        self.seccion_metas.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.seccion_metas.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.seccion_metas.setObjectName("seccion_metas")
        self.verticalLayout_2.addWidget(self.seccion_metas)
        self.seccion_progreso = QtWidgets.QFrame(parent=self.widget)
        self.seccion_progreso.setMinimumSize(QtCore.QSize(400, 20))
        self.seccion_progreso.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.seccion_progreso.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.seccion_progreso.setObjectName("seccion_progreso")
        self.verticalLayout_2.addWidget(self.seccion_progreso)
        self.seccion_recomendacions = QtWidgets.QFrame(parent=self.widget)
        self.seccion_recomendacions.setMinimumSize(QtCore.QSize(400, 20))
        self.seccion_recomendacions.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.seccion_recomendacions.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.seccion_recomendacions.setObjectName("seccion_recomendacions")
        self.verticalLayout_2.addWidget(self.seccion_recomendacions)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)

        self.retranslateUi(PanelMetas)
        QtCore.QMetaObject.connectSlotsByName(PanelMetas)

    def retranslateUi(self, PanelMetas):
        _translate = QtCore.QCoreApplication.translate
        PanelMetas.setWindowTitle(_translate("PanelMetas", "Form"))
        self.label.setText(_translate("PanelMetas", "Metas Financieras"))
        self.label_2.setText(_translate("PanelMetas", "Define y rastrea tus objetivos de ahorro e inversión"))
        self.btn_nueva_meta.setText(_translate("PanelMetas", "Nueva Meta"))
