# Form implementation generated from reading ui file 'panel_reportes.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PanelReportes(object):
    def setupUi(self, PanelReportes):
        PanelReportes.setObjectName("PanelReportes")
        PanelReportes.resize(640, 480)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PanelReportes)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=PanelReportes)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.contenedor_reportes = QtWidgets.QScrollArea(parent=PanelReportes)
        self.contenedor_reportes.setWidgetResizable(True)
        self.contenedor_reportes.setObjectName("contenedor_reportes")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 628, 444))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.contenedor_reportes.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.contenedor_reportes)

        self.retranslateUi(PanelReportes)
        QtCore.QMetaObject.connectSlotsByName(PanelReportes)

    def retranslateUi(self, PanelReportes):
        _translate = QtCore.QCoreApplication.translate
        PanelReportes.setWindowTitle(_translate("PanelReportes", "Form"))
        self.label.setText(_translate("PanelReportes", "Reportes:"))
