# Form implementation generated from reading ui file 'panel_presupuestos.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PanelPresupuestos(object):
    def setupUi(self, PanelPresupuestos):
        PanelPresupuestos.setObjectName("PanelPresupuestos")
        PanelPresupuestos.resize(640, 480)
        self.gridLayout_2 = QtWidgets.QGridLayout(PanelPresupuestos)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 192, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(92, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=PanelPresupuestos)
        self.label.setMinimumSize(QtCore.QSize(160, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=PanelPresupuestos)
        self.label_2.setMinimumSize(QtCore.QSize(160, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.SeccionPresupuestos = QtWidgets.QFrame(parent=PanelPresupuestos)
        self.SeccionPresupuestos.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.SeccionPresupuestos.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.SeccionPresupuestos.setObjectName("SeccionPresupuestos")
        self.gridLayout.addWidget(self.SeccionPresupuestos, 2, 0, 1, 2)
        self.btn_agregar_presupuesto = QtWidgets.QPushButton(parent=PanelPresupuestos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(140)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_agregar_presupuesto.sizePolicy().hasHeightForWidth())
        self.btn_agregar_presupuesto.setSizePolicy(sizePolicy)
        self.btn_agregar_presupuesto.setObjectName("btn_agregar_presupuesto")
        self.gridLayout.addWidget(self.btn_agregar_presupuesto, 0, 1, 2, 1)
        self.SeccionResumen = QtWidgets.QFrame(parent=PanelPresupuestos)
        self.SeccionResumen.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.SeccionResumen.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.SeccionResumen.setObjectName("SeccionResumen")
        self.gridLayout.addWidget(self.SeccionResumen, 3, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(91, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 192, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 1, 1, 1)

        self.retranslateUi(PanelPresupuestos)
        QtCore.QMetaObject.connectSlotsByName(PanelPresupuestos)

    def retranslateUi(self, PanelPresupuestos):
        _translate = QtCore.QCoreApplication.translate
        PanelPresupuestos.setWindowTitle(_translate("PanelPresupuestos", "Form"))
        self.label.setText(_translate("PanelPresupuestos", "Gestión de Presupuestos"))
        self.label_2.setText(_translate("PanelPresupuestos", "Crea y monitorea tus presupuestos mensuales"))
        self.btn_agregar_presupuesto.setText(_translate("PanelPresupuestos", "Nuevo Presupuesto"))
